#!/bin/bash
# FFmpeg Stream Forwarder Configuration Generator
# Creates scripts to forward RTSP streams from Reolink NVR to Cloudflare Stream

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo "================================================"
echo "  FFmpeg Stream Forwarder Setup"
echo "================================================"
echo ""

# NVR Configuration
NVR_HOST="hwmnbn.myddns.me:554"
NVR_USER="hwmnbn"
NVR_PASS="@codecam22"

echo -e "${YELLOW}This script will create FFmpeg forwarding configurations.${NC}"
echo ""
echo -e "${BLUE}IMPORTANT:${NC} Before running this script:"
echo "  1. Deploy your Worker"
echo "  2. Visit the Worker URL"
echo "  3. Click 'Initialize Streams'"
echo "  4. Copy the RTMP ingest URLs for each camera"
echo ""

read -p "Have you completed the steps above? (y/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo -e "${RED}Please complete the setup first, then run this script again.${NC}"
    exit 1
fi

echo ""
echo -e "${YELLOW}Choose deployment method:${NC}"
echo "  1) Bash script (simple, run manually)"
echo "  2) Systemd services (Linux production)"
echo "  3) Docker Compose (recommended)"
echo "  4) All of the above"
echo ""
read -p "Enter choice (1-4): " choice

# Collect RTMP URLs
declare -a RTMP_URLS

echo ""
echo -e "${YELLOW}Enter RTMP ingest URLs for each camera:${NC}"
echo "(Format: rtmps://live.cloudflare.com:443/live/YOUR_STREAM_KEY)"
echo ""

for i in {1..7}; do
    printf "Camera $i RTMP URL: "
    read url
    RTMP_URLS[$i]=$url
done

echo ""

# Generate Bash Script
if [[ $choice == "1" ]] || [[ $choice == "4" ]]; then
    echo -e "${YELLOW}Generating bash script...${NC}"

    cat > stream-all-cameras.sh << 'EOF'
#!/bin/bash
# Stream all Reolink cameras to Cloudflare Stream
# Generated by create-stream-forwarder.sh

set -e

# Configuration
NVR_HOST="hwmnbn.myddns.me:554"
NVR_USER="hwmnbn"
NVR_PASS="@codecam22"

# RTMP URLs from Cloudflare Stream
EOF

    for i in {1..7}; do
        echo "RTMP_URL_$i=\"${RTMP_URLS[$i]}\"" >> stream-all-cameras.sh
    done

    cat >> stream-all-cameras.sh << 'EOF'

# Function to stream a camera
stream_camera() {
    local camera_num=$1
    local rtmp_url=$2

    local rtsp_url="rtsp://${NVR_USER}:${NVR_PASS}@${NVR_HOST}/h264Preview_$(printf %02d $camera_num)_main"

    echo "Starting stream for Camera $camera_num..."

    ffmpeg -rtsp_transport tcp \
        -i "$rtsp_url" \
        -c:v copy \
        -c:a copy \
        -f flv \
        "$rtmp_url" \
        2>&1 | sed "s/^/[Camera $camera_num] /" &
}

# Start all cameras
echo "Starting all camera streams..."
echo "Press Ctrl+C to stop all streams"
echo ""

EOF

    for i in {1..7}; do
        echo "stream_camera $i \"\$RTMP_URL_$i\"" >> stream-all-cameras.sh
    done

    cat >> stream-all-cameras.sh << 'EOF'

# Wait for all background processes
wait
EOF

    chmod +x stream-all-cameras.sh
    echo -e "${GREEN}✓ Created: stream-all-cameras.sh${NC}"
fi

# Generate Systemd Services
if [[ $choice == "2" ]] || [[ $choice == "4" ]]; then
    echo -e "${YELLOW}Generating systemd service files...${NC}"

    mkdir -p systemd-services

    for i in {1..7}; do
        cat > systemd-services/reolink-camera-$i.service << EOF
[Unit]
Description=Reolink Camera $i Stream Forwarder
After=network.target
Wants=network-online.target

[Service]
Type=simple
Restart=always
RestartSec=10
User=$USER

Environment="RTSP_URL=rtsp://${NVR_USER}:${NVR_PASS}@${NVR_HOST}/h264Preview_$(printf %02d $i)_main"
Environment="RTMP_URL=${RTMP_URLS[$i]}"

ExecStart=/usr/bin/ffmpeg -rtsp_transport tcp -i \${RTSP_URL} -c:v copy -c:a copy -f flv \${RTMP_URL}

StandardOutput=journal
StandardError=journal
SyslogIdentifier=reolink-cam$i

[Install]
WantedBy=multi-user.target
EOF
    done

    # Create installation script
    cat > systemd-services/install.sh << 'EOF'
#!/bin/bash
# Install systemd services

if [ "$EUID" -ne 0 ]; then
    echo "Please run with sudo"
    exit 1
fi

echo "Installing systemd services..."

for service in reolink-camera-*.service; do
    cp "$service" /etc/systemd/system/
    systemctl enable "$service"
    echo "Installed and enabled: $service"
done

systemctl daemon-reload
echo ""
echo "Services installed. Start them with:"
echo "  sudo systemctl start reolink-camera-{1..7}"
EOF

    chmod +x systemd-services/install.sh
    echo -e "${GREEN}✓ Created systemd services in systemd-services/${NC}"
    echo "  To install: cd systemd-services && sudo ./install.sh"
fi

# Generate Docker Compose
if [[ $choice == "3" ]] || [[ $choice == "4" ]]; then
    echo -e "${YELLOW}Generating docker-compose.yml...${NC}"

    cat > docker-compose.yml << 'EOF'
version: '3.8'

services:
EOF

    for i in {1..7}; do
        cat >> docker-compose.yml << EOF
  camera-$i:
    image: linuxserver/ffmpeg:latest
    container_name: reolink-cam-$i
    restart: unless-stopped
    network_mode: host
    command: >
      -rtsp_transport tcp
      -i rtsp://${NVR_USER}:${NVR_PASS}@${NVR_HOST}/h264Preview_$(printf %02d $i)_main
      -c:v copy
      -c:a copy
      -f flv
      ${RTMP_URLS[$i]}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

EOF
    done

    echo -e "${GREEN}✓ Created: docker-compose.yml${NC}"
    echo "  To start: docker-compose up -d"
fi

echo ""
echo "================================================"
echo -e "${GREEN}  Setup Complete!${NC}"
echo "================================================"
echo ""
echo "Generated files:"
if [[ $choice == "1" ]] || [[ $choice == "4" ]]; then
    echo "  - stream-all-cameras.sh (bash script)"
fi
if [[ $choice == "2" ]] || [[ $choice == "4" ]]; then
    echo "  - systemd-services/ (systemd configuration)"
fi
if [[ $choice == "3" ]] || [[ $choice == "4" ]]; then
    echo "  - docker-compose.yml (Docker Compose)"
fi
echo ""

echo "Next steps:"
echo ""

if [[ $choice == "1" ]] || [[ $choice == "4" ]]; then
    echo -e "${YELLOW}Bash Script:${NC}"
    echo "  ./stream-all-cameras.sh"
    echo ""
fi

if [[ $choice == "2" ]] || [[ $choice == "4" ]]; then
    echo -e "${YELLOW}Systemd Services:${NC}"
    echo "  cd systemd-services"
    echo "  sudo ./install.sh"
    echo "  sudo systemctl start reolink-camera-{1..7}"
    echo ""
fi

if [[ $choice == "3" ]] || [[ $choice == "4" ]]; then
    echo -e "${YELLOW}Docker Compose:${NC}"
    echo "  docker-compose up -d"
    echo "  docker-compose logs -f  # View logs"
    echo ""
fi

echo "================================================"
